language: php
php:
  - 5.6
before_script:
  - tests/install-wp-tests.sh wordpress_test root '' localhost latest
# - mysql -e "create database IF NOT EXISTS wordpress-test;" -uroot
  - composer install
  - composer db
notifications:
  email:
    - andrzej.max.marcinkowski@gmail.com
