language: php
php:
  - 5.6
before_script:
  - mysqladmin create wordpress_test --user=root
  - cp resources/.env ~
  - composer install
  - composer db
  - mkdir -p build/logs
script:
  - composer test
after_script:
  - php vendor/bin/coveralls
